version: "2" # required to adjust maintainability checks
plugins:
  phpcodesniffer:
    enabled: true
  phan:
    enabled: true
    channel: "beta"
    config:
      file_extensions: "php"
      ignore-undeclared: true
  phpmd:
    enabled: true
ratings:
  paths:
    - app/**
    - database/**
exclude_patterns:
  - .idea
  - .phan
  - bootstrap
  - docker
  - docs
  - public
  - resources
  - storage
  - database/**
