name: Generate Deptract Modules Diagram

on:
  push:
    branches:
      - main
      - master
      - develop

jobs:
  deptrac-modules-diagram:
    name: Generate Deptract Modules Diagram
    runs-on: ubuntu-latest
    container:
      image: escolalms/php:8
      

    steps:
      - name: Instantiate package
        uses: actions/checkout@v2        

      - name: Update composer
        run: |
          apt-get install unzip -y
          composer self-update
          composer update --no-scripts
          composer require qossmic/deptrac-shim --no-scripts

      - name: Install git & graphviz
        run: | 
          add-apt-repository universe
          apt update
          apt-get install git graphviz -y

      - name: Generage deptrac-modules.yaml
        run: php deptrac.php

      - name: Generage deptrac-diagram.yaml
        run:  ./vendor/bin/deptrac analyse --config-file=deptrac-modules.yaml --formatter=graphviz-image --output=deptrac-modules.png
        continue-on-error: true

      - name: Archive  deptrac-diagram
        uses: actions/upload-artifact@v3
        with:
          name: deptrac-modules.png
          path: deptrac-modules.png
        
        


