name: Generate Deptract Modules Diagram

on:
  push:
    branches:
      - main
      - master
      - develop

jobs:
  deptrac-modules-diagram:
    name: Generate Deptract Modules Diagram
    runs-on: ubuntu-latest
    container:
      image: escolalms/php:8
      

    steps:
      - name: Instantiate package
        uses: actions/checkout@v2        

      - name: Update composer
        run: |
          apt-get install unzip -y
          composer self-update
          composer update --no-scripts
          composer require qossmic/deptrac-shim --no-scripts

      - name: Install git & graphviz
        run: | 
          apt-get update
          apt-get install git graphviz graphviz-dev -y

      - name: Generage deptrac-modules.yaml
        run: php deptrac.php && mkdir deptrac

      - name: Generage deptrac-diagram.yaml
        run:  ./vendor/bin/deptrac analyse --config-file=deptrac-modules.yaml --formatter=graphviz-image --output=deptrac/deptrac-modules.png
        continue-on-error: true

      - name: Archive  deptrac-diagram
        uses: actions/upload-artifact@v3
        with:
          name: deptrac-modules.png
          path: deptrac/deptrac-modules.png

     
      - name: Deploy to external repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.STATS_KEY }}

        with:
          # GitHub Action output files
          source-directory: deptrac/
          destination-github-username: qunabu
          destination-repository-name: EscolaLMS/.github
          user-email: <your email>
          # It defaults to `main`
          target-branch: "main"

      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY     
        
        


