name: Publish development Package to dockerhub
on:
  repository_dispatch:
  workflow_dispatch:
  push:
    branches:
      - 'develop'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile.develop
          push: true
          tags: escolalms/api:${{github.ref_name}}
          platforms: linux/amd64
          
      - name: Send webook to mattermost
        uses: TNT-Likely/webhook-action@V0.1.0
        env:
          verbose: true
          webhookUrl: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
          data: '{ "text": "There is a new [escolalms/api:develop](https://hub.docker.com/r/escolalms/api/tags?page=1&name=develop) image built. k8s rollout will happen soon" }'

      - name: Send webook to hooks to rollout all devs on k8s 
        uses: TNT-Likely/webhook-action@V0.1.0 
        env:
          webhookUrl: ${{ secrets.K8S_WEBHOOK_URL_API_DEVELOP }}
