name: Generate Swagger Documentation

on:
  push:
    branches:
      - main
      - master
      - develop

jobs:
  swagger-gh-pages:
    runs-on: ubuntu-latest
    container:
      image: escolalms/php:7.4

    steps:
      - name: Instantiate package
        uses: actions/checkout@v2

      - name: Prepare Laravel Application
        run: |
          cp docker/envs/.env.ci.mysql .env
          cp docker/envs/phpunit.xml.mysql phpunit.xml

      - name: Update composer
        run: composer update

      - name: Generage openapi
        run: php artisan l5-swagger:generate

      - name: Swagger ui action
        id: swagger-ui-action
        uses: pjoc-team/swagger-ui-action@v0.0.2
        with:
          dir: "./storage/api-docs/"
          pattern: "api-docs.json"
          debug: "true"

      - name: Install git
        run: apt-get install git -y

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: swagger-ui
